name: Selenium Test

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Install ChromeDriver
        run: |
          set -ex 
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install ./google-chrome-stable_current_amd64.deb

      - name: Install Allure
        run: |
          wget https://github.com/allure-framework/allure2/releases/download/2.17.3/allure-2.17.3.zip
          unzip allure-2.17.3.zip -d /opt
          sudo ln -s /opt/allure-2.17.3/bin/allure /usr/local/bin/allure
          allure --version

      - name: Get history allure
        run: |
          # Clona el repositorio en la carpeta gh-pages
          git clone --branch=gh-pages --single-branch --depth=1 https://github.com/rcampos09/SeleniumDonTester.git gh-pages
          chmod -R +r gh-pages/allure-report/history
          ls -la gh-pages/allure-report/history
          pwd

      - name: Run Selenium Tests And Report 
        run: |
          set +e  # Desactiva la detección de errores para continuar ejecutando incluso si las pruebas fallan
          ls -la
          mvn clean test -Denv=urlStaging -Dremote=false || true  # Ejecuta las pruebas y continúa incluso si fallan
          set -e  # Vuelve a activar la detección de errores
          ls -la gh-pages/allure-report/history
          cp gh-pages/allure-report/history target/allure-results/history
          allure generate target/allure-results --clean
          ls -la

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: ./allure-report
          # Añade este comando para copiar el historial al directorio de publicación cada vez que se ejecuta la suite
          post_script: |
          # cp -R allure-report/history allure-report/allure-results/history
