name: Selenium Test

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Install ChromeDriver
        run: |
          set -ex 
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install ./google-chrome-stable_current_amd64.deb

      - name: Install Allure
        run: |
          wget https://github.com/allure-framework/allure2/releases/download/2.17.3/allure-2.17.3.zip
          unzip allure-2.17.3.zip -d /opt
          sudo ln -s /opt/allure-2.17.3/bin/allure /usr/local/bin/allure
          allure --version

      - name: Run Selenium Tests And Report 
        run: |
          mvn clean test -Denv=urlStaging -Dremote=false
          allure generate target/allure-results --clean

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report
